server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

bank.simulator.url=${BANK_SIMULATOR_URL:http://localhost:8080}

gateway.supported-currencies=USD,GBP,EUR

spring.jackson.deserialization.accept-float-as-int=false